name: botx
description: An application client for BotX service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  http: ^0.12.1
  flutter_spinkit: ^4.1.2
  flutter_polyline_points: ^0.2.2
  auto_route: ^0.2.1
  fluttertoast: ^7.0.1
  google_maps_webservice: ^0.0.17
  flutter_google_places: ^0.2.5
  flutter_vlc_player: ^3.0.3
  percent_indicator: ^2.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.2.1+3

flutter:
  uses-material-design: true
  assets:
    - map/